# -*- coding: utf-8 -*-
"""Question2_Copy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jAzv7ms2qgkF5VSG2RFIVBIE7324NsRI

### Question 2 (20 points)

(1 pts) Create a dictionary.
Its keys consist of students' names and the values consist of **the list of students' grades**.  
(2 pts) Take both the student names and the student grades from the user. 

(3 pts) Continue taking students' names until a user enters **-1**. 

(3 pts) Each time, check whether a user enter the same name before. (In this class, everyone has a unique name.)

(2 pts) Take exactly **three** grades for each student.

(3pts) Each grade should be a **positive number including zero**, please check each grade whether it meets this condition. 

(3pts) Calculate the average grade for each student and print it on the screen. 

(3pts) Check the dictionary below, which shows the grading scale, and determine the letter grade of each student based on it. Add the letter grades of the students at the end of the student's grade lists and print the final version of the dictionary. 

grading_scale = {'A': '100-90', 'B': '89-70', 'C': '69-60', 'D': '59-50', 'F': '49-0'}
"""

# Mounting Google drive in Colab and assigning path
from google.colab import drive
import pandas as pd
drive.mount("/content/drive")
path = '//content//drive//MyDrive//DS 8015 Midterm//Question2//'

mythisdict = {
}

import numpy as np

while 1:
    val = input("Enter the name of student: ")
    if val == "-1":
      break 
    if val in mythisdict.keys():
      print("Duplicate name ... ")
      continue
    grade_arr = []
    i = 0
    while (i<3):
      grade = input("Enter the grade: " )
      grade = float(grade)
      if (grade < 0):
        print("please Enter valid garde ...")
        continue
      if (grade >= 0):
        i = i + 1
        grade_arr.append(grade)
    grade_arr_append =  np.array(grade_arr)

    mythisdict.update({val: grade_arr})

mythisdict

newlist = list()
for i in mythisdict.keys():
  newlist.append(i)
print(newlist)

import statistics
avg = []
for i in range(len(mythisdict)):
  x = mythisdict.get(newlist[i])
  mean_data = statistics.mean(x)
  avg.append(mean_data)
  print("The name of Student : ", newlist[i])
  print("the avg is :", mean_data)

grading_scale = {'A': '100-90', 'B': '89-70', 'C': '69-60', 'D': '59-50', 'F': '49-0'}

newlist_grade_scale = list()
for i in grading_scale.keys():
  newlist_grade_scale.append(i)
print(newlist_grade_scale)

for j in range(len(avg)):
  for i in range(len(grading_scale)):
    txt = grading_scale.get(newlist_grade_scale[i])
    x = txt.split("-")
    if ((avg[j]<float(x[0])) and (avg[j]>float(x[1]))):
      name = newlist[j]
      mythisdict[name].append(newlist_grade_scale[i])

print(mythisdict)